# Travis CI integration file for ESP-IDF v4.1

os: linux
dist: focal
language: shell

addons:
  apt:
    packages:
    - git
    - wget
    - flex
    - bison
    - gperf
    - python3
    - python3-pip
    - python3-setuptools
    - python-is-python3
    - cmake
    - ninja-build
    - ccache
    - libffi-dev
    - libssl-dev

install:
  - mkdir ~/esp
  - cd ~/esp
  - git clone -b v4.1 --recursive https://github.com/espressif/esp-idf.git
  - cd ~/esp/esp-idf
  - ./install.sh
  - . ~/esp/esp-idf/export.sh

script:
  - cd $TRAVIS_BUILD_DIR/example
  - idf.py reconfigure
  - idf.py app

after_success:
  - cd $TRAVIS_BUILD_DIR/example
  - idf.py size

branches:
  only:
  - main
