# Travis CI integration file for
# esp-idf "stable" release
#
# In 2020.07.16 the stable release was v4.0.1

os: linux
dist: xenial
language: shell

addons:
  apt:
    packages:
    - git
    - wget
    - libncurses-dev
    - flex
    - bison
    - gperf
    - python
    - python-pip
    - python-setuptools
    - cmake
    - ninja-build
    - ccache
    - libffi-dev
    - libssl-dev

install:
  - mkdir ~/esp
  - cd ~/esp
  - git clone -b v4.0.1 --recursive https://github.com/espressif/esp-idf.git
  - cd ~/esp/esp-idf
  - ./install.sh
  - . ~/esp/esp-idf/export.sh

script:
  - cd $TRAVIS_BUILD_DIR/example
  - idf.py reconfigure
  - idf.py app

after_success:
  - cd $TRAVIS_BUILD_DIR/example
  - idf.py size

branches:
  only:
  - master
