name: Build with ESP-IDF v4.2

on: [push]

jobs:
  builder:
    name: Builder for the test project
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ESP32HAL

      - name: Build
        uses: CalinRadoni/esp-idf-v4-container-action@v4.2
        id: execution
        with:
          entrypoint: /github/workspace/ESP32HAL/test/action-build.sh

      - name: Compute SHA256 for bin and elf files
        if: steps.execution.outputs.result == 0
        run: |
          file="${{ github.workspace }}/ESP32HAL/test/build/test-ESP32HAL.bin"
          hash=$(sha256sum -b "$file")
          stat -c"$hash %s" "$file"
          file="${{ github.workspace }}/ESP32HAL/test/build/test-ESP32HAL.elf"
          hash=$(sha256sum -b "$file")
          stat -c"$hash %s" "$file"
