name: Build with ESP-IDF v4.1

on: [push]

jobs:
  builder:
    name: Builder for the test project
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ESP32HAL

      - name: Build
        uses: CalinRadoni/esp-idf-v4-container-action@v4.1
        id: execution
        with:
          entrypoint: /github/workspace/ESP32HAL/test/action-build.sh
